import localFont from "next/font/local";
import "./globals.css";
import DataProvider from "@/context/DataProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Coordinadora",
  description: "Generated by create next app",
};

async function getTerminals() {
  const res = await fetch(`https://apiv2-test.coordinadora.com/cm-maestros-territorios-ms/api/v1/terminales`)
  return res.json();
}

export default async function RootLayout({ children }) {
    //Terminales
    const dataTerminal = await getTerminals();

  return (
    
    <html lang="es">
      <DataProvider dataTerminal={dataTerminal}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </DataProvider>
    </html>
  );
}

